GET http://localhost:3001/events HTTP/1.1

###

POST http://localhost:3001/events/new HTTP/1.1
Content-Type: application/json

{
    "homeTeam": "jako",
    "awayTeam": "koji",
    "location": "CENG Gymnasium",
    "division": "male",
    "winner": "koji",
    "sport": "2007"
}

###

DELETE http://localhost:3001/events/delete/645280c8c89fae13f5e2b938 HTTP/1.1